---
sidebar: sidebar 
permalink: ONTAP/fix-blockers-warnings.html 
keywords: fix ontap blockers and warnings, ontap update precheck, acknowledge warnings 
summary: 'Correggere i blocchi ONTAP e confermare gli avvisi che impediscono di completare l"aggiornamento ONTAP.' 
---
= Correggere tutti i blocchi utilizzando gli aggiornamenti del software BlueXP  prima di un aggiornamento di ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver identificato la versione di destinazione di ONTAP per il sistema di storage ONTAP, è necessario correggere e riconoscere tutti i blocchi e rivedere gli avvisi prima di aggiornare il sistema di storage ONTAP.

.Ruolo BlueXP richiesto:
Amministratore dell'organizzazione, amministratore di cartelle o progetti, amministratore di archiviazione o specialista dell'integrità del sistema. link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso BlueXP."^]

La correzione e la conferma di tutti i blocchi è obbligatoria e garantisce un processo di aggiornamento del software senza interruzioni.

.Fasi
. Dal menu di navigazione BlueXP  sinistro, selezionare *integrità > aggiornamenti software*.
+
Viene visualizzato l'elenco dei cluster che richiedono un aggiornamento software.

. Identifica la versione di destinazione di ONTAP per il tuo sistema storage. Per informazioni sull'identificazione della versione di destinazione di ONTAP, vedere link:../ONTAP/choose-ontap-910-later.html["Confrontare le versioni di ONTAP per comprendere i vantaggi e i rischi derivanti dall'uso degli aggiornamenti software di BlueXP "].
. Dopo aver scelto la versione di destinazione ONTAP , selezionare *Prepara per l'aggiornamento* per avviare il processo di aggiornamento.
+
Viene visualizzato l'elenco dei blocchi e delle avvertenze.

. Selezionare il blocco per visualizzare le istruzioni per correggere il blocco.
. Eseguire manualmente i passaggi forniti per correggere il blocco.
. Seleziona i blocchi che sono stati risolti e seleziona *Riconosci selezione* per confermare che i blocchi sono stati risolti.



NOTE: È necessario correggere e confermare tutti i blocchi per procedere con l'aggiornamento.

. Selezionare la scheda *Avvisi* per leggere gli avvisi prima di procedere con l'aggiornamento software.
. Selezionare la scheda *Riconosci* per visualizzare i blocchi che sono stati risolti.
. Selezionare *Continua ad aggiornare* per procedere con il processo di aggiornamento.

