---
sidebar: sidebar 
permalink: ONTAP/fix-blockers-warnings.html 
keywords: fix ontap blockers and warnings, ontap update precheck, acknowledge warnings 
summary: 'Correggere i blocchi ONTAP e confermare gli avvisi che impediscono di completare l"aggiornamento ONTAP.' 
---
= Correggere e riconoscere i blocchi ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver identificato la versione di destinazione di ONTAP per il sistema di storage ONTAP, è necessario correggere e riconoscere tutti i blocchi e rivedere gli avvisi prima di aggiornare il sistema di storage ONTAP.

La correzione e la conferma di tutti i blocchi è obbligatoria e garantisce un processo di aggiornamento del software senza interruzioni.

.Fasi
. Dal menu di navigazione BlueXP  sinistro, selezionare *integrità > aggiornamenti software*.
+
Viene visualizzato l'elenco dei cluster che richiedono un aggiornamento software.

. Identifica la versione di destinazione di ONTAP per il tuo sistema storage. Per informazioni sull'identificazione della versione di destinazione di ONTAP, vedere link:../ONTAP/choose-ontap-910-later.html["Scegliere la versione di destinazione ONTAP 9,10 o successiva"].
. Dopo aver deciso la versione di destinazione di ONTAP, fare clic su *prepara per l'aggiornamento* per avviare il processo di aggiornamento.
+
Viene visualizzato l'elenco dei blocchi e delle avvertenze.

. Selezionare il blocco per visualizzare le istruzioni per correggere il blocco.
. Eseguire manualmente i passaggi forniti per correggere il blocco.
. Selezionare i blocchi che sono stati corretti e fare clic su *Conferma selezione* per confermare che i blocchi sono stati corretti.



NOTE: È necessario correggere e confermare tutti i blocchi per procedere con l'aggiornamento.

. Fare clic sulla scheda *Avvertenze* per rivedere gli avvisi prima di procedere con l'aggiornamento del software.
. Fare clic sulla scheda *Conferma* per visualizzare i blocchi che sono stati corretti.
. Fare clic su *continua per aggiornare* per procedere con il processo di aggiornamento.

