---
sidebar: sidebar 
permalink: ONTAP/update-storage-system.html 
keywords: update ontap storage system 
summary: Aggiorna il tuo sistema di storage ONTAP per sfruttare le nuove e migliorate funzioni. 
---
= Aggiornamento completo del sistema storage ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver identificato la versione di destinazione di ONTAP, corretto e riconosciuto tutti i blocchi, è possibile completare l'aggiornamento del sistema di storage ONTAP.

.Fasi
. Dal menu di navigazione BlueXP  sinistro, selezionare *integrità > aggiornamenti software*.
+
Viene visualizzato l'elenco dei cluster che richiedono un aggiornamento software.

. Identifica la versione di destinazione di ONTAP per il tuo sistema storage. Per informazioni sull'identificazione della versione di destinazione di ONTAP, vedere link:../ONTAP/choose-ontap-910-later.html["Scegliere la versione di destinazione ONTAP 9,10 o successiva"].
. Correggere e riconoscere i blocchi ONTAP. Per informazioni sul fissaggio dei blocchi, vedere link:../ONTAP/fix-blockers-warnings.html["Correggere e riconoscere i blocchi ONTAP"].
. Leggere e accettare il contratto di licenza per l'utente finale.
+
Attendere il recupero dell'immagine ONTAP.

. Fare clic su *Installa aggiornamento* per completare il processo di aggiornamento.

