---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'software updates, ontap update, what"s new, enhancements' 
summary: Comprendere le nuove funzioni e i miglioramenti introdotti negli aggiornamenti software BlueXP . 
---
= Novità degli aggiornamenti software BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le novità degli aggiornamenti software BlueXP .



== 02 aprile 2025



=== Rischi mitigati

Nella sezione riepilogativa degli aggiornamenti software BlueXP , è ora possibile visualizzare il numero totale di rischi che possono essere mitigati dall'aggiornamento del sistema operativo. Ciò consente agli utenti di valutare i miglioramenti della sicurezza e della stabilità nella base di installazione.



== 07 agosto 2024



=== Aggiornamento ONTAP

Il servizio di aggiornamenti software di BlueXP  offre agli utenti un'esperienza di aggiornamento senza problemi, riducendo i rischi e garantendo ai clienti la possibilità di sfruttare appieno le funzionalità di ONTAP.

Ulteriori informazioni su link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["Aggiornamenti software BlueXP "].
